[[redirects]]
	from = "/index"
	to = "/index.html"
	status = 200
[[redirects]]
	from = "/iso"
	to = "/iso.html"
	status = 200
[[redirects]]
	from = "/support"
	to = "/support.html"
	status = 200
[[redirects]]
	from = "/"
	to = "/404.html"
	status = 404